export enum Priority {
  BLOCKER = 'BLOCKER',
  CRITICAL = 'CRITICAL',
  VERY_HIGH = 'VERY_HIGH',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  VERY_LOW = 'VERY_LOW',
  OPTIONAL = 'OPTIONAL'
}
