apiVersion: v1
kind: Service
metadata:
  name: story-tasks-ui
  namespace: uhmarcel
  labels:
    name: story-tasks
spec:
  type: NodePort
  selector:
    app: story-tasks-ui
  ports:
    - name: entry
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-tasks-ui
  namespace: uhmarcel
  labels:
    name: story-tasks
spec:
  selector:
    matchLabels:
      app: story-tasks-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: story-tasks-ui
    spec:
      containers:
        - name: story-tasks-ui
          image: uhmarcel/story-tasks-ui:0.17.9
          env:
            - name: BACKEND_URL
              value: http://$(STORY_TASKS_API_SERVICE_HOST):8080
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
